# Generated by Django 3.2.4 on 2021-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Current_Address_of_Pharmacy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='IdProofNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='Work_experience',
            field=models.CharField(choices=[('', 'Select Year of Experience'), ('1', '1 Year'), ('2', '2 Year'), ('3', '3 Year'), ('4', '4 Year'), ('5', '4+ years'), ('6', '10+ years'), ('7', 'None')], max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(choices=[('', 'Select City'), ('1', 'Delhi'), ('2', 'Nairobi'), ('3', 'Mombasa'), ('4', 'Kiambu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(choices=[('', 'Select Country'), ('1', 'Axis'), ('2', 'Nairobi'), ('3', 'Mombasa'), ('4', 'Kiambu')], max_length=4),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female'), ('TRNS', 'Transgender'), ('NSP', 'Not Specified')], max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='qualification',
            field=models.CharField(choices=[('', 'Select Year of Experience'), ('1', '1 Year'), ('2', '2 Year'), ('3', '3 Year'), ('4', '4 Year'), ('5', '4+ years'), ('6', '10+ years'), ('7', 'None')], max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='type_of_pharmacy',
            field=models.CharField(choices=[('', 'Type of Pharmacy'), ('1', 'Community'), ('2', 'Hospital'), ('3', 'PHC'), ('4', 'Government'), ('5', 'Non-Government'), ('6', 'Other'), ('7', 'No Pharmacy')], max_length=5),
        ),
    ]
